steps:
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy-environs
  args:
    - cp
    - -r
    - 'gs://${_TARGET_PROJECT_}-configs/workbench/src/environments/'
    - ./src/
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy-app
  args:
    - cp
    - 'gs://${_TARGET_PROJECT_}-configs/workbench/src/app.yaml'
    - ./src/

- name: 'justingrayston/chrome_node:latest'
  id: install
  args: ['npm', 'install']
  waitFor:
    - copy-environs
    - copy-app
# - name: 'justingrayston/chrome_node:latest'
#   args: ['npm', 'run', 'test-ci']
# - name: 'selenium/standalone-chrome-debug:latest'
#   args: ['npm', 'run', 'e2e']
- name: 'justingrayston/chrome_node:latest'
  id: build
  args: ['npm', 'run', 'build']
  waitFor:
    - install
- name: 'gcr.io/cloud-builders/gcloud'
  id: deploy
  args:
    - app
    - deploy
    - ./dist/app.yaml
    - --project=${_TARGET_PROJECT_}
  waitFor:
    - build
- name: 'gcr.io/cloud-builders/gcloud'
  id: gzip
  entrypoint: /bin/sh
  args:
    - -c
    - |
      tar cvzf dist.tar.gz dist
  waitFor:
    - build
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_}/workbench/${_TARGET_PROJECT_}/$SHORT_SHA'
    paths: ['dist.tar.gz']
